---
  - name: Start photoprism
    block:
      - name: Create Prism group
        group:
          name: prism
          gid: "{{ photoprism_group_id }}"
          state: present

      - name: Create Prism user
        user:
          name: prism
          uid: "{{ photoprism_user_id }}"
          state: present
          system: yes
          update_password: on_create
          create_home: no
          group: prism

      - name: "Create prism Directories"
        file:
          path: "{{ item }}"
          state: directory
          owner: "{{photoprism_user_id}}"
          group: "{{photoprism_group_id}}"
          # mode: 0755
        with_items:
          - "{{ photoprism_config_directory }}"
          - "{{ photoprism_compose_directory }}"
          - "{{ photoprism_storage }}"
          - "{{ photoprism_import }}"
          - "{{ photoprism_letsencrypt }}"
          
      - name: Template over docker-compose.yml file
        template:
          src: templates/docker-compose.yml
          dest: "{{photoprism_compose_directory}}/docker-compose.yml"
          owner: prism
          group: prism

      - name: Template over acme.json
        template:
          src: templates/acme.json
          dest: "{{photoprism_letsencrypt}}/acme.json"
          owner: prism
          group: prism

      # - name: Stop existing photoprism
      #   docker_compose:
      #     build: no
      #     stopped: yes
      #     project_src: "{{photoprism_compose_directory}}"
 
      - name: Build Photoprism
        docker_compose:
          state: present
          build: yes
          project_src: "{{ photoprism_compose_directory }}"

      - name: Start Photoprism
        docker_compose:
          build: no
          project_src: "{{ photoprism_compose_directory }}"

      - name: Add superuser to Photoprism
        docker_compose:
          build: no 
          project_src: "{{ photoprism_compose_directory }}"
          exec: "photoprism users add --name {{primary_user}} --password {{primary_user_passwd}} -w -s {{primary_user}} "

      - name: Add users to Photoprism
        docker_compose:
          build: no 
          project_src: "{{ photoprism_compose_directory }}"
          exec: "photoprism users add --name {{item.comment}} --email {{item.email}} --password {{item.password}} -w {{item.name}} "
        loop: "{{ regular_users }}"


      - name: Add extra users to Photoprism
        docker_compose:
          build: no 
          project_src: "{{ photoprism_compose_directory }}"
          exec: "photoprism users add --name {{item.comment}} --email {{item.email}} --password {{item.password}} -w {{item.name}} "
        loop: "{{ extra_users }}"

    when: photoprism_enabled is true

  - name: Stop Photoprism
    block:
      - name: Stop Photoprism
        docker_container:
          name: "{{ photoprism_container_name }}"
          state: absent
        register: result

      - name: Check Photoprism is stopped
        assert:
          that:
            - not result.changed
    when: photoprism_enabled is false
