---
- name: Start Deluge
  block:
    - name: Create service group
      group:
        name: "{{service_group_name}}"
        gid: "{{ service_group_id }}"
        state: present

    - name: Create service user
      user:
        name: "{{service_user_name}}"
        uid: "{{ service_user_id }}"
        state: present
        system: yes
        update_password: on_create
        create_home: no
        group: "{{service_group_name}}"

    - name: Create service Directories
      file:
        path: "{{ item }}"
        state: directory
        user: "{{service_user_id}}"
        group: "{{service_group_id}}"
      with_items:
        - "{{ service_config_directory }}"
        - "{{ service_download_directory }}"

    - name: Template over docker-compose.yml file
      template:
        src: "templates/docker-compose.yml"
        dest: "{{service_config_directory}}/docker-compose.yml"
        owner: paperless
        group: paperless

    - name: Stop existing service
      docker_compose:
        build: no
        stopped: yes
        project_src: "{{ service_config_directory }}"

    - name: Build service
      docker_compose:
          state: present
          build: yes
          project_src: "{{ service_config_directory }}"

    - name: Start service
      docker_compose:
        build: no
        project_src: "{{ service_config_directory }}"
  
  when: deluge_enabled is true

- name: Stop Deluge
  block:
    - name: Stop Deluge
      docker_container:
        name: "{{ service_container_name }}"
        state: absent
  when: deluge_enabled is false
