version: "2"
services:
  homer:
    image: b4bz/homer
    #To build from source, comment previous line and uncomment below
    #    #build: .
    container_name: {{homer_container_name}}
    volumes:
      - {{homer_assets_directory }}:/www/assets
    ports:
      - "{{ homer_port }}:8080"
    user: {{homer_user_id}}:{{homer_group_id}} # default
    environment:
      - INIT_ASSETS={{homer_init_assets}} # default
    restart: unless-stopped
