---
- name: "Create required directories in /etc/letsencrypt"
  file:
    path: "/etc/letsencrypt/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=x,o=x
  with_items:
    - account
    - certs
    - csrs
    - keys

- name: Install certbot ddns_packages
  apt:
    name: "python3, libaugeas0, python3-certbot"
    state: present
  register: result
  until: result is succeeded

- name: Request certificate
  shell: "{{certbot_path }} certonly --standalone --domains {{ domain_name }} --email {{ acme_email }} --agree-tos -n"
  become: yes

- name: Verify certificates
  shell: '{{certbot_path}}  certificates | grep "Certificate Name: {{domain_name}} " '
  become: yes

- name: Add scripts to renew certificates
  block:
    - name: Service template
      template:
        src: templates/certbot.service
        dest: /etc/snapraid.conf/etc/systemd/system/certbot.service
        owner: root
        group: root
        mode: 0775

    - name: Time template
      template:
        src: templates/certbot.timer
        dest: /etc/snapraid.conf/etc/systemd/system/certbot.timer
        owner: root
        group: root
        mode: 0775

    - name: reload systemd
      ansible.builtin.systemd:
        name: certbot.timer
        enabled: true
  when: letsencrypt_renewal_enabled is true
#cp /etc/letsencrypt/live/$FQDN/fullchain.pem /etc/cockpit/ws-certs.d/$FQDN.crt
#cp /etc/letsencrypt/live/$FQDN/privkey.pem /etc/cockpit/ws-certs.d/$FQDN.key
# Note: The user and group may be different
# chown cockpit-ws:cockpit-ws /etc/cockpit/ws-certs.d/$FQDN.crt /etc/cockpit/ws-certs.d

#/etc/letsencrypt/renewal-hooks/post/001-restart-cockpit.sh⌗
#!/usr/bin/env bash

# echo "SSL certificates renewed"

# cp /etc/letsencrypt/live/$FQDN/fullchain.pem /etc/cockpit/ws-certs.d/$FQDN.crt
# cp /etc/letsencrypt/live/$FQDN/privkey.pem /etc/cockpit/ws-certs.d/$FQDN.key
# chown cockpit-ws:cockpit-ws /etc/cockpit/ws-certs.d/$FQDN.crt /etc/cockpit/ws-certs.d/$FQDN.key

# echo "Restarting Cockpit"
# systemctl restart cockpit
