---
- name: "Create required directories in /etc/letsencrypt"
  file:
    path: "/etc/letsencrypt/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=x,o=x
  with_items:
    - account
    - certs
    - csrs
    - keys

- name: Install certbot ddns_packages
  apt:
    name: "python3, libaugeas0, python3-certbot"
    state: present
  register: result
  until: result is succeeded

# Check if nginx is running if so install python3-certbot-nginx

- name: Gathering service facts
  service_facts:

- name: stop nginx if it is running  
  service: 
    name: nginx
    state: stopped
  ignore_errors: true 

- name: stop apache2 if it is running  
  service: 
    name: apache2
    state: stopped
  ignore_errors: true 

- name: Request certificate
  shell: "{{certbot_path }} certonly --standalone --domains {{ domain_name }} --email {{ acme_email }} --agree-tos -n"
  become: true

- name: Verify certificates
  shell: '{{certbot_path}}  certificates | grep "Certificate Name: {{domain_name}} " '
  become: true

- name: Add scripts to renew certificates
  block:
    - name: Service template
      template:
        src: templates/certbot.service
        dest: /etc/snapraid.conf/etc/systemd/system/certbot.service
        owner: root
        group: root
        mode: 0775

    - name: Time template
      template:
        src: templates/certbot.timer
        dest: /etc/snapraid.conf/etc/systemd/system/certbot.timer
        owner: root
        group: root
        mode: 0775

    - name: reload systemd
      ansible.builtin.systemd:
        name: certbot.timer
        enabled: true
  when: letsencrypt_renewal_enabled is true

# echo "Restarting Cockpit"
# systemctl restart cockpit
