---
- name: install letsencrypt Certificates
  block:
    - name: debug
      debug:
        msg: letsencrypt_install

    - name: install via certbox
      include_tasks: roles/ansible-letsencrypt/tasks/install-certbot.yml
      when: letsencrypt_install == 'certbot'

    - name: install via ansible
      include_tasks: roles/ansible-letsencrypt/tasks/install-ansible.yml
      when: letsencrypt_install == 'ansible'
  when: (letsencrypt_enabled is true)
