---
- name: Create ansible-nas group
  group:
    name: ansible-nas
    state: present

- name: Create ansible-nas user
  user:
    name: ansible-nas
    state: present
    system: yes
    update_password: on_create
    create_home: no
    group: ansible-nas
    shell: /usr/sbin/nologin

- name: Ensure authorized key for root user is installed
  authorized_key:
    user: root
    state: present
    key: "{{ ssh_pub_key }}"
  when: ssh_pub_key | d(False)

- name: "Create/update primary user with sudo privileges"
  user:
    name: "{{ primary_user }}"
    password: "{{ primary_user_passwd | password_hash('sha512') }}"
    state: present
    groups: "sudo, users"
    append: true
    shell: /bin/bash

- name: "Ensure authorized keys for remote user is installed"
  authorized_key:
    user: "{{ primary_user }}"
    state: present
    key: "{{ ssh_pub_key }}"
  when: ssh_pub_key | d(False) and primary_user | d(False)

- name: Update root user password.
  user:
    name: root
    password: "{{ root_passwd | password_hash('sha512') }}"

- name: Create/Update regular user_passwd
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    groups: users
    state: present
    password: "{{ item.password  | password_hash('sha512') }}"
    append: true
    shell: /bin/bash
  loop: "{{ regular_users }}"
