---
- name: Install paperless-ngx
  block:
  - name: Create paperless group
    group:
        name: paperless
        gid: "{{ paperless_ng_group_id }}"
        state: present

  - name: Create paperless user
    user:
      name: paperless
      uid: "{{ paperless_ng_user_id }}"
      state: present
      system: yes
      update_password: on_create
      create_home: no
      group: paperless

  - name: Create paperless_ng directories
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "{{ paperless_ng_config_directory }}"
      - "{{ paperless_ng_files_directory }}"
      - "{{ paperless_ng_postgres_directory }}"
      - "{{ paperless_ng_data_directory }}"
      - "{{ paperless_ng_export_directory }}"
      - "{{ paperless_ng_media_directory }}"
      - "{{ paperless_ng_consume_directory }}"


  - name: Template over docker-compose.yml file
    template:
        src: "templates/docker-compose.yml"
        dest: "{{paperless_ng_config_directory}}/docker-compose.yml"
        owner: paperless
        group: paperless

  - name: Stop existing service
    docker_compose:
        build: no
        stopped: yes
        project_src: "{{ paperless_ng_config_directory }}"

  - name: Build service
    docker_compose:
        state: present
        build: yes
        project_src: "{{ paperless_ng_config_directory }}"

  - name: Start service
    docker_compose:
        build: no
        project_src: "{{ paperless_ng_config_directory }}"
  
  when: paperless_ng_enabled is true 