---
photoprism_enabled: false
photoprism_available_externally: false

# directories
photoprism_config_directory: "{{ docker_home }}/prism/config"
photoprism_storage: "{{ docker_home }}/prism/storage"
photoprism_photos_directory: "{{ photos_root }}"

# uid / gid
photoprism_user_id: "0"
photoprism_group_id: "0"

# If you're paranoid, set permissions to "ro" so Prism won't ever be able to
# delete your files
photoprism_photos_permissions: "rw"

# network
photoprism_hostname: "https://dsmhome.ddns.net"
photoprism_path: "/photoprism"
# specs
photoprism_memory: "2g"

# Device mappings for the docker container. E.g. To enable hardware transcoding:
# photoprism_devices:
#  - "/dev/dri:/dev/dri"
photoprism_port: 2345
photoprism_database_dir:
photoprism_database_name: "photoprism"
photoprism_database_user: "photoprism"
photoprism_password: "insecure"
photoprism_root_password: "insecure"
photoprism_watchtower_cleanup: true
photoprism_watchtower_poll: 7200

# see https://hub.docker.com/r/linuxserver/plex for details on this setting
photoprism_version: "docker"
photoprism_container_name: photoprism
photoprism_db_container_name: photoprism_mariadb
