---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - include_vars:
        file: ../../defaults/main.yml

    - name: Try and stop and remove photoprism
      docker_container:
        name: "{{ photoprism_container_name }}"
        state: absent
      register: result

    - name: Check Photoprism is stopped
      assert:
        that:
          - not result.changed
