---
- name: Install DUC (NOIP) client
  block:
    - name: Download DUC client
      ansible.builtin.unarchive:
        src: "{{ download_url }}"
        dest: /tmp
        remote_src: yes

    - name: Install package
      apt:
        deb: "/tmp/{{deb_package}}"
        state: present

    # - name: Test configuration file
    #   shell: /usr/bin/noip-duc  --username "{{ ddns_username }}" --password "{{ ddns_password }}" --once
    #   become: true

    - name: Create cofiguration file
      template:
        owner: root
        group: root
        src: templates/noip-duc
        dest: /etc/noip-duc

    - name: Copy service file
      template:
        owner: root
        group: root
        src: templates/duc-service
        dest: /etc/systemd/system/noip-duc.service

    - name: set to run ddns on boot
      ansible.builtin.systemd:
        name: "{{service_name}}"
        state: started
        enabled: true
      when: ddns_boot_at_start is true

  when: ddns_client == "duc"
