---
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      skip: true
  tags:
    - vars
    - install

- name: Install DDNS
  block:
    - name: include ddns client variables
      include_vars: "{{ ddns_client }}.yml"
      tags:
        - install
        - config
        - start-service

    # - name: Check that client has an install file {{ ddns_client }}
    #   stat:
    #     path: "/tasks/{{ ddns_client}}.yml"
    #   register: install_file
    - name: Run specific steps for client
      ansible.builtin.include_tasks: "tasks/{{ ddns_client}}.yml"
      tags:
        - always
        - install
        - config
      # when: install_file.stat.exists

  when: (ansible_ddns_enabled == true)
