---
- name: Start Heimdall
  block:
    - name: Create Heimdall group
      group:
        name: heimdall
        gid: "{{ heimdall_group_id }}"
        state: present

    - name: Create Heimdall user
      user:
        name: heimdall
        uid: "{{ heimdall_user_id }}"
        state: present
        system: yes
        update_password: on_create
        create_home: no
        group: heimdall

    - name: Create Heimdall Directories
      file:
        path: "{{ item }}"
        state: directory
        owner: heimdall
        group: heimdall
      with_items:
        - "{{ heimdall_data_directory }}"
        - "{{ heimdall_config_directory }}"

    - block:
        - name: Build local docker version
          ansible.builtin.include_tasks: "tasks/build_docker.yml"

        - name: Set heimdall_docker_image
          set_fact:
            heimdall_docker_image: "heimdall_local"
      when: heimdall_build_locally is true

    - block:
        - name: Customize container
          ansible.builtin.include_tasks: "tasks/customize_container.yml"
      when: heimdall_customize_container is true

    - name: copy Docker compose file
      template:
        src: "templates/docker-compose.yml"
        dest: "{{ heimdall_compose_directory }}/docker-compose.yml"
        owner: nextcloud

    - name: Build heimdall
      docker_compose:
        state: present
        build: yes
        project_src: "{{ heimdall_compose_directory }}"

    - name: Start heimdall
      docker_compose:
        build: no
        project_src: "{{ heimdall_compose_directory }}"

    - name: Pre-install Applications
      template:
        src: "templates/HeimdallExport.json"
        dest: "{{heimdall_data_directory}}/HeimdallImport.json"
      when: heimdall_pre_install_apps is true
  when: heimdall_enabled is true

- name: Stop Heimdall
  block:
    - name: Stop Heimdall
      docker_container:
        name: "{{ heimdall_container_name }}"
        state: absent
  when: heimdall_enabled is false
