---
- name: Start radarr
  block:
      - name: Create radarr group
        group:
          name: radarr
          gid: "{{ radarr_group_id }}"
          state: present

      - name: Create radarr user
        user:
          name: radarr
          uid: "{{ radarr_user_id }}"
          state: present
          system: yes
          update_password: on_create
          create_home: no
          group: radarr
          groups: "{{samba_force_group}}"

      - name: Create radarr Directories
        file:
          path: "{{ item }}"
          state: directory
        with_items:
          - "{{ radarr_data_directory }}"

      - name: Template over docker-compose.yml file
        template:
          src: templates/docker-compose.yml
          dest: "{{radarr_compose_directory}}/docker-compose.yml"
          owner: radarr
          group: radarr

      # - name: Stop existing photoprism
      #   docker_compose:
      #     build: no
      #     stopped: yes
      #     project_src: "{{photoprism_compose_directory}}"
 
      - name: Build docker
        docker_compose:
          state: present
          build: yes
          project_src: "{{ radarr_compose_directory }}"

      - name: Start docker
        docker_compose:
          build: no
          project_src: "{{ radarr_compose_directory }}"
  when: radarr_enabled is true
