---
- name: Create user
  community.docker.docker_container_exec:
    container: nextcloud_app
    env: 
      OC_PASS: "{{default_user_password}}"
    argv:
      - "php"
      - "occ"
      - "user:add"
      - "--display-name={{item.comment}}"
      - "--password-from-env"
      - "{{item.name}}"
  register: result
  loop: "{{regular_users}}"

- name: Add email
  community.docker.docker_container_exec:
    container: nextcloud_app
    argv:
      - "php"
      - "occ"
      - "user:setting"
      - "{{item.name}}"
      - "settings"
      - "email"
      - "{{item.email}}"
  register: result
  loop: "{{regular_users}}"

- name: Change quota
  community.docker.docker_container_exec:
      container: nextcloud_app
      argv:
        - "php"
        - "occ"
        - "user:setting"
        - "{{item.name}}"
        - "files"
        - "quota"
        - "{{ nextcloud_user_quota}}"
  register: result
  loop: "{{regular_users}}"
