version: '3.5'
services:
  paperless_ng_redis:
    container_name: "{{paperless_ng_container_name_redis}}"
    image: "redis:6.0"
    restart: unless-stopped

  paperless_ng_postgres:
    container_name: "{{paperless_ng_container_name_postgres}}"
    image: "postgres:13"
    volumes:
      - "{{paperless_ng_postgres_directory}}:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: "{{paperless_ng_postgres_db}}"
      POSTGRES_USER: "{{paperless_ng_postgres_user}}"
      POSTGRES_PASSWORD: "{{paperless_ng_postgres_password}}"
    restart: unless-stopped

  paperless_ng_ui:
    container_name: "{{paperless_ng_container_name_uiserver}}"
    image: "jonaswinkler/paperless-ng:latest"
    volumes:
      - "{{paperless_ng_data_directory}}:/usr/src/paperless/data"
      - "{{paperless_ng_media_directory}}:/usr/src/paperless/media"
      - "{{paperless_ng_export_directory}}:/usr/src/paperless/export"
      - "{{paperless_ng_consume_directory}}:/usr/src/paperless/consume"
    ports:
      - "{{paperless_ng_port}}:8000"
    environment:
      PAPERLESS_REDIS: "redis://paperless_ng_redis:6379"
      PAPERLESS_DBHOST: "paperless_ng_postgres"
      USERMAP_UID: "{{paperless_ng_user_id}}"
      USERMAP_GID: "{{paperless_ng_group_id}}"
      PAPERLESS_OCR_LANGUAGES: "{{paperless_ng_languages}}"
      PAPERLESS_OCR_LANGUAGE: "{{paperless_ng_language}}"
      PAPERLESS_FILENAME_FORMAT: "{{paperless_ng_file_format}}"
      PAPERLESS_FILENAME_DATE_ORDER: "DMY"
      PAPERLESS_DATE_ORDER: "DMY"
    restart: unless-stopped