network:
  version: 2
  renderer: networkd
  ethernets:
    {{item}}:
      addresses:
        - {{static_address}}/{{static_map}}
      routes:
        - to: default
          via: 10.10.10.1
      nameservers:
          search: [mydomain, otherdomain]
          addresses: [10.10.10.1, 1.1.1.1]