---
##                       ._____.   .__
##  _____    ____   _____|__\_ |__ |  |   ____             ____ _____    ______
##  \__  \  /    \ /  ___/  || __ \|  | _/ __ \   ______  /    \\__  \  /  ___/
##   / __ \|   |  \\___ \|  || \_\ \  |_\  ___/  /_____/ |   |  \/ __ \_\___ \
##  (____  /___|  /____  >__||___  /____/\___  >         |___|  (____  /____  >
##       \/     \/     \/        \/          \/               \/     \/     \/
##     a n s i b l e - n a s      https://github.com/davestephens/ansible-nas

# Add your all.yml config overrides to this file. See group_vars/all.yml for all possible settings.

# Ansible options
ansible_nas_hostname: dsmhome
ansible_nas_timezone: "Asia/Jerusalem"

primary_user: "hda_admin"
ssh_pub_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5MmEhwd7q59uGEyeX2VajxXdU/MXPmYD5on7Gfn+WIFREnYbnstQKxrpyk78UikW1V9diNU0qBIGbnpXyzlCGMz3tMH4+SNxSbBmKCVR4itMscyoMBIhOUjyl/OF7idYrNQa95BV/MArh/n6XN1wpJywqTTR++Clhex4o32DeqTUDpNQhTkpmjJTFLi7JK13NcSCUO2ceFNsP6FiKlgrlliTErEf6qdCi/HqBmQgXBn75YvVG7771bElzGlI/XkyCmSOo/bDU+4y6M9D5HecK64YNHG1g8ipZaPekbUZqUo5LjNlhPIsIZqTHz8J0Ld0vE2MO4ByH5TSkUreRgS0T creating SSH"

samba_enabled: true
samba_shares_root: /mnt/storage/samba # We don't want it in Mount - we want it in the pools
samba_server_string: "DSM NAS"
samba_users:
  - name: arnon
    password: "{{ default_user_password}}"
  - name: ava
    password: "{{ default_user_password}}"
  - name: yael
    password: "{{ default_user_password}}"
  - name: racheli
    password: "{{ default_user_password}}"
  - name: yonatan
    password: "{{ default_user_password}}"

# Shares you want published over Samba.
samba_shares:
  - name: downloads
    comment: "Stuff downloaded"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ downloads_root }}"

  - name: movies
    comment: "Movies"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ movies_root }}"

  - name: tv
    comment: "TV Episodes"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ tv_root }}"

  - name: music
    comment: "Music"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ music_root }}"

  - name: dump
    comment: "File dump"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ samba_shares_root }}/dump"

  - name: photos
    comment: "Pictures"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ photos_root }}"

  - name: documents
    comment: "Documents"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ documents_root }}"

  - name: code
    comment: "Code"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ code_root }}"

nfs_shares_root:
nfs_exports:

###
### Brazarr
###
brazarr_enabled: true
bazarr_data_directory: "{{ docker_home }}/bazarr/config"
bazarr_compose_directory: "{{ docker_home }}/bazarr/config"

###
### Cockpit
###
cockpit_enabled: true
cockpit_started: true
cockpit_port: 9090
cockpit_packages: full

###
### Mergefs
###
mergerfs_enabled: true
# mergerfs_install_mode: package_manager
mergerfs_install_mode: "source"
mergerfs_minfreespace: "2G"
mergerfs_fsname: "mergefs"
mergerfs_mounts:
  - path: /mnt/storage
    branches:
      - /mnt/disk*
    options: defaults,allow_other,use_ino,cache.files=partial,dropcacheonclose=true,category.create=mfs,minfreespace={{mergerfs_minfreespace}},fsname={{mergerfs_fsname}}

###
### Docker
###
docker_users:
  - arnon

# Area for all the configuration files of the applicaiton in containers
docker_home: /mnt/storage/docker
# Area of all the containers themselves
docker_image_directory: "{{ docker_home }}/data"

###
### Traefik
###
traefik_enabled: true
certEmail: "{{ ansible_nas_email }}"

portainer_enabled: true
portainer_data_directory: "{{ docker_home }}/portainer/config"

photoprism_enabled: true
photoprism_available_externally: true
photoprism_compose_directory: "{{ docker_home }}/prism/config"
photoprism_storage: "{{ docker_home }}/prism/storage"
photoprism_database_dir: "{{ docker_home }}/prism/db"
photoprism_photos_directory: "{{ photos_root }}"
photoprism_config_directory: "{{ docker_home }}/prism/config"
photoprism_hostname: "https://{{ansible_nas_fqdn}}"

heimdall_enabled: true
heimdall_port_http: 8081
heimdall_data_directory: "{{ docker_home }}/heimdall" # Needs to be changed

homer_enabled: false
homer_port: "8082"
homer_compose_directory: "{{samba_shares_root}}/homer"

bazarr_enabled: true
radarr_enabled: true
deluge_enabled: true
jackett_enabled: true
sonarr_enabled: true

plex_enabled: true
#plex_devices:
#  - "/dev/dri:/dev/dri"

route53_ddns_enabled: false
route53_host: "{{ansible_nas_hostname}}.{{ ansible_nas_domain }}"

snapraid_enabled: true
snapraid_install: true
snapraid_runner: true
snapraid_content_files:
  - /var/snapraid.content
snapraid_data_disks:
  - path: /mnt/disk1
    content: true
  - path: /mnt/disk2
    content: true
  # - path: /mnt/disk3
  # - path: /mnt/disk4
snapraid_parity_disks:
  - path: /mnt/parity1
    content: true

## Keys for ansible-disk
disk_enabled: true
additional_fs_utils:
  - xfsprogs # package for mkfs.xfs on RedHat / Ubuntu
  - btrfs-progs # package for mkfs.btrfs on CentOS / Debian

disk_additional_disks:
  - disk: /dev/sdb
    fstype: ext4
    mount_options: defaults
    mount: /mnt/parity1
    user: root
    group: root
    mode: "0755"
    #  disable_periodic_fsck: false
  - disk: /dev/sdc
    fstype: ext4
    mount_options: defaults
    mount: /mnt/disk1
    user: root
    group: root
    mode: "0755"
  - disk: /dev/sdd
    fstype: ext4
    mount_options: defaults
    mount: /mnt/disk2
    user: root
    group: root
    mode: "0755"
disk_enable_partioning: false

ansible_ddns_enabled: true
ddns_client: "google_ddns"
ddns_packages: []
ddclient_user: root
ddns_config_files: []
ddns_service: ""
ddns_boot_at_start: false

# Gmail Credentials
google_domain_protocol: "googledomains"
google_domain_login: "testuser"
google_domain_password: "testpassword"
google_domain_ddns: "ddns-domain.test"

timemachine_enabled: true
timemachine_data_directory: "{{samba_shares_root}}/timemachine"

webmin_enabled: false
webmin_base_dir: "/usr/share/webmin"

letsencrypt_enabled: false

cloudberry_enabled: true
