---
version: "3"

services:
  db:
    image: "{{nextcloud_mysql_image}}"
    container_name: nextcloud_mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - "{{ nextcloud_compose_directory }}/db:/var/lib/mysql:Z"
    env_file:
      - "{{ nextcloud_db_envfile }}"
      

  app:
    image: "{{nextcloud_app_image}}"
    container_name: nextcloud_app
    restart: always
    depends_on:
      - db
    ports:
      - "{{nextcloud_port}}:80"
    volumes:
      - "{{ nextcloud_compose_directory }}/nextcloud:/var/www/html:z"
    env_file:
      - "{{ nextcloud_db_envfile }}"
    user: "{{nextcloud_user_id }}:83"
    labels:
      traefik.enable: "{{ nextcloud_available_externally | string }}"
      traefik.http.routers.nextcloud.rule: "Host(`{{ ansible_nas_fqdn }}`) && PathPrefix(`{{nextcloud_path}}`)"
      traefik.http.routers.nextcloud.tls.certresolver: "letsencrypt"
      traefik.http.routers.nextcloud.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.nextcloud.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.nextcloud.loadbalancer.server.port: "80"

  # web: 
  #   build: ./web
  #   container_name: nextcloud_web
  #   restart: always
  #   ports:
  #     - "{{nextcloud_port}}:80"
  #   volumes:
  #     - "{{ nextcloud_compose_directory }}/nextcloud:/var/www/html:z"
  #   depends_on:
  #     - app

  cron:
    image: nextcloud:apache
    container_name: nextcloud_cron
    restart: always
    volumes:
      - "{{ nextcloud_compose_directory }}/nextcloud:/var/www/html:z"
    entrypoint: /cron.sh
    depends_on:
      - db

volumes:
  nextcloud:
  db: