---
- name: Start sonarr
  block:
      - name: Create sonarr group
        group:
          name: sonarr
          gid: "{{ sonarr_group_id }}"
          state: present

      - name: Create sonarr user
        user:
          name: sonarr
          uid: "{{ sonarr_user_id }}"
          state: present
          system: yes
          update_password: on_create
          create_home: no
          group: sonarr

      - name: Create Sonarr Directories
        file:
          path: "{{ item }}"
          state: directory
        with_items:
          - "{{ sonarr_data_directory }}"

      - name: Template over docker-compose.yml file
        template:
          src: templates/docker-compose.yml
          dest: "{{sonarr_compose_directory}}/docker-compose.yml"
          owner: prism
          group: prism

      # - name: Stop existing photoprism
      #   docker_compose:
      #     build: no
      #     stopped: yes
      #     project_src: "{{photoprism_compose_directory}}"
 
      - name: Build docker
        docker_compose:
          state: present
          build: yes
          project_src: "{{ sonarr_compose_directory }}"

      - name: Start docker
        docker_compose:
          build: no
          project_src: "{{ sonarr_compose_directory }}"
  when: sonarr_enabled is true
