---
- name: Start Bazarr
  block:
    - name: Create Bazarr group
      group:
        name: bazarr
        gid: "{{ bazarr_group_id }}"
        state: present

    - name: Create bazarr user
      user:
        name: bazarr
        uid: "{{ bazarr_user_id }}"
        state: present
        system: yes
        update_password: on_create
        create_home: no
        group: bazarr

    - name: Create Bazarr Directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ bazarr_data_directory }}"

    - name: Template over docker-compose.yml file
      template:
        src: templates/docker-compose.yml
        dest: "{{bazarr_compose_directory}}/docker-compose.yml"
        owner: "{{ bazarr_user_id }}"
        group: "{{ bazarr_group_id }}"

    - name: Build Bazzar
      docker_compose:
        state: present
        build: yes
        project_src: "{{ bazarr_compose_directory }}"

    - name: Start Bazarr
      docker_compose:
        build: no
        project_src: "{{ bazarr_compose_directory }}"
  when: bazarr_enabled is true

- name: Stop Bazarr
  block:
    - name: Stop Bazarr
      docker_container:
        name: "{{ bazarr_container_name }}"
        state: absent
  when: bazarr_enabled is false
