version: "3.5"
services:
  bazarr:
    container_name: {{bazarr_container_name}} 
    image: "linuxserver/bazarr"
    volumes:
      - "{{ bazarr_tv_directory }}:/tv:rw"
      - "{{ bazarr_movies_directory }}:/movies:rw"
      - "{{ bazarr_data_directory }}:/config:rw"
    ports:
      - "{{ bazarr_port }}:6767"
    environment:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ bazarr_user_id }}"
      PGID: "{{ bazarr_group_id }}"
    restart: unless-stopped
    # memory: "{{ bazarr_memory }}"
    labels:
      traefik.enable: "{{ bazarr_available_externally | string }}"
      traefik.http.routers.bazarr.rule: "Host(`{{ ansansible_nas_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.bazarr.tls.certresolver: "letsencrypt"
      traefik.http.routers.bazarr.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.bazarr.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.bazarr.loadbalancer.server.port: "6767"