version: '3.5'

services:
    {{service_name}}:
      container_name: "{{service_container_name}}"
      image: "{{service_image_name}}"
      volumes:
        - "{{ service_download_directory }}:/downloads:rw"
        - "{{ service_config_directory }}:/config:rw"
      ports:
        - "{{ service_port }}:{{service_port}}"
        - "6881:6881"
        - "6881:6881/udp"
      environment:
        TZ: "{{ ansible_nas_timezone }}"
        PUID: "{{ service_user_id }}"
        PGID: "{{ service_group_id }}"
      restart: unless-stopped
      # memory: "{{ radarr_memory }}"
      # traefik.enable: "{{ deluge_available_externally | string }}"
          # traefik.http.routers.deluge.rule: "Host(`{{ deluge_hostname }}.{{ ansible_nas_domain }}`)"
          # traefik.http.routers.deluge.tls.certresolver: "letsencrypt"
          # traefik.http.routers.deluge.tls.domains[0].main: "{{ ansible_nas_domain }}"
          # traefik.http.routers.deluge.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          # traefik.http.services.deluge.loadbalancer.server.port: "8112"
