---
- name: Create Traefik Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ traefik_data_directory }}"
    - "{{ traefik_data_directory }}/data"
    - "{{ traefik_data_directory }}/data/config"

- name: copy Traefik config file
  template:
    src: templates/traefik.yaml
    dest: "{{ traefik_data_directory }}/data/traefik.yaml"
  register: template_config

- name: copy ha config file
  template:
    src: templates/ha.yaml
    dest: "{{ traefik_data_directory }}/data/config/ha.yaml"
  register: template_config

- name: Template over docker-compose.yml file
  template:
    src: templates/docker-compose.yml
    dest: "{{traefik_data_directory}}/docker-compose.yml"

- name: Build docker
        docker_compose:
          state: present
          build: yes
          project_src: "{{ traefik_data_directory }}"

      - name: Start docker
        docker_compose:
          build: no
          project_src: "{{ traefik_data_directory }}"
  when: traefik_enabled is true
