---
- name: Install Plex
  block:
    - name: Create Plex group
      group:
        name: plex
        gid: "{{ plex_group_id }}"
        state: present

    - name: Create Plex user
      user:
        name: plex
        uid: "{{ plex_user_id }}"
        state: present
        system: yes
        update_password: on_create
        create_home: no
        group: plex

    - name: Create Plex Directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{plex_user_id}}"
        group: "{{plex_group_id}}"
        # mode: 0755
      with_items:
        - "{{ plex_config_directory }}"
        - "{{ plex_logs }}"

    - name: Template over docker-compose.yml file
      template:
        src: "templates/docker-compose.yml"
        dest: "{{plex_compose_directory}}/docker-compose.yml"
        owner: plex
        group: plex

    - name: Stop existing plex
      docker_compose:
        build: no
        stopped: yes
        project_src: "{{ plex_compose_directory }}"
    # - assert:
    #     that:
    #       - "not plex.state.running"

    - name: Build plex
      docker_compose:
        state: present
        build: yes
        project_src: "{{ plex_compose_directory }}"

    - name: Start Plex
      docker_compose:
        build: no
        project_src: "{{ plex_compose_directory }}"
  when: plex_enabled is true

- name: Stop Plex
  block:
    - name: Stop Plex
      docker_container:
        name: "{{ plex_container_name }}"
        state: absent
      register: result

    - name: Check Plex is stopped
      assert:
        that:
          - not result.changed
  when: plex_enabled  is false
