---
- name: Install Cloud Berry
  block:
    - name: Copy package to host
      copy:
        remote_src: false
        src: "files/{{ local_dep_filename }}"
        dest: /tmp/

    - name: copy configuration file
      copy:
        remote_src: false
        src: "files/export.cbbconfiguration"
        dest: /tmp/

    - name: Download and install package
      apt:
        deb: "/tmp/{{ local_dep_filename }}"
        state: present
        update_cache: true

    - name: Register Licenese
      ansible.builtin.command:
        chdir: "{{cloudberry_path}}"
        cmd: './cbb activateLicense  -e "{{ansible_nas_email}}" -k "{{license_key}}" '

    - name: Enabled web interface
      ansible.builtin.command:
        chdir: "{{cloudberry_path}}"
        cmd: "./cbb option -set wa -http on"
  
    - name: Import configuration
      ansible.builtin.command:
        chdir: "{{ cloudberry_path }}"
        cmd: "./cbb importConfig -f /tmp/export.cbbconfiguration -m"
        
  when: cloudberry_enabled is true
